import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import BackgroundMusicPlayer from "./components/partial/BackGroundMusic";
import AdBanner from "./components/partial/AdBanner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`custom-cursor ${inter.className}`}>
        <BackgroundMusicPlayer />
        {children}
        <AdBanner />
      </body>
    </html>
  );
}
